### ISSUE TITLE
Assembling error

### ISSUE THREAD

**Issue by sevsnine** [CalebFenton/resequencer#1]
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[105,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[105,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[105,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[105,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[105,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[105,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[105,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[171,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[171,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[171,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[171,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[171,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[171,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[171,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[188,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[188,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[188,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[188,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\app\ActionBarDrawerToggleHoneycomb.smali[188,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[108,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[108,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[108,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[108,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[108,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[108,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[108,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[166,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[166,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[166,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[166,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[166,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[166,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\text\ICUCompatIcs.smali[166,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\view\ViewPager.smali[8684,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\view\ViewPager.smali[8684,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\view\ViewPager.smali[8684,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\view\ViewPager.smali[8684,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\view\ViewPager.smali[8684,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\view\ViewPager.smali[8684,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\view\ViewPager.smali[8684,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\widget\SlidingPaneLayout$SlidingPanelLayoutImplJB.smali[119,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\widget\SlidingPaneLayout$SlidingPanelLayoutImplJB.smali[119,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\widget\SlidingPaneLayout$SlidingPanelLayoutImplJB.smali[119,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\widget\SlidingPaneLayout$SlidingPanelLayoutImplJB.smali[119,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\widget\SlidingPaneLayout$SlidingPanelLayoutImplJB.smali[119,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\widget\SlidingPaneLayout$SlidingPanelLayoutImplJB.smali[119,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\android\support\v4\widget\SlidingPaneLayout$SlidingPanelLayoutImplJB.smali[119,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$FloatPropertyValuesHolder.smali[139,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$FloatPropertyValuesHolder.smali[139,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$FloatPropertyValuesHolder.smali[139,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$FloatPropertyValuesHolder.smali[139,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$FloatPropertyValuesHolder.smali[139,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$FloatPropertyValuesHolder.smali[139,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$FloatPropertyValuesHolder.smali[139,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$IntPropertyValuesHolder.smali[139,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$IntPropertyValuesHolder.smali[139,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$IntPropertyValuesHolder.smali[139,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$IntPropertyValuesHolder.smali[139,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$IntPropertyValuesHolder.smali[139,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[767,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[767,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[767,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[767,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[767,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[767,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[767,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$IntPropertyValuesHolder.smali[139,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder$IntPropertyValuesHolder.smali[139,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[964,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[964,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[964,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[964,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[964,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[964,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[964,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[1226,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[1226,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[1226,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[1226,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[1226,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[1226,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\internal\nineoldandroids\animation\PropertyValuesHolder.smali[1226,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[152,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[152,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[152,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[152,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[152,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[152,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[152,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[179,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[179,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[179,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[179,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\view\MenuInflater$InflatedOnMenuItemClickListener.smali[179,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1296,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1296,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1296,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1296,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1296,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1296,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1296,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1352,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1352,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1352,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1352,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1352,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1352,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1352,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1361,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1361,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1361,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1361,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[1361,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2377,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2377,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2377,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2377,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2377,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2377,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2377,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2445,32] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2445,33] Error for input '!': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2445,34] mismatched input 'Hook' expecting set null
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2445,44] Error for input '/': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2445,60] Error for input '.ReflectedInvoke': Invalid directive
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2445,76] Error for input '%': Invalid text
Kinozal_tv_1.3.6_sequenced-dump\smali\com\actionbarsherlock\widget\SearchView.smali[2445,45] mismatched input 'ReflectedInvoke' expecting END_METHOD_DIRECTIVE

**Comment by CalebFenton** [comment]
Could you provide the APK, Smali, or md5 / sha1 of the apk or dex? I'm 99% sure the problem is that resequencer is bundled with smali 1.x and the syntax changed in smali 2.x. Then there's the 1% chance it resequenced improperly.

**Comment by sevsnine** [comment]
http://rghost.net/8kDlFwRRV

**Comment by CalebFenton** [comment]
Thanks for packaging that together so nicely. I finally had some time to look at this, and figured out what it was. I went ahead and converted everything to Gradle and tidied up a bit, so if you pull and rebuild it should work.

However, in case you don't want to, the fix can be done by modifying `hooks.xml`:
This part near the top:

```
%!Hook:hooks/ReflectedInvoke.ReflectedInvoke%
```

Should be

```
%!Hook:hooks/ReflectedInvoke.invokeHook%
```

Feel free to re-open if you still have problems.
