### ISSUE TITLE
Does it still work ?

### ISSUE THREAD

**Issue by Karim0x1** [CalebFenton/resequencer#12]
Hello,
Sorry to bother, I know that this is an old project but do you think it still works ? I don't know how It works internally and I don't really want to get into it if it's outdated. Hope it's not though, it would be very useful for me.
Thank you

**Comment by CalebFenton** [comment]
You probably don't want to use this approach and it's a little outdated. Resequencer disassembles an apk to smali, then runs some clever regex & replace & insert on the smali, then rebuilds the apk. This approach is robust, but I haven't used this in years and assume it would take at least a few hours to get working again, especially if you want to update some of the dependencies. Resequencer fine when you want to patch an apk and have it run anywhere, but if it's just for your own device, it's better to use frida.

I'm closing the issue, but feel free to carry on the discussion here.
